#!/usr/bin/env python3
"""Generate p4src/generated_params.p4 from config/default.yaml.

All constants derive from the YAML file — no duplication across unrelated files.
"""

import sys
import yaml
from pathlib import Path

TEMPLATE = """// PTT-INT: Generated parameters
// Auto-generated by control/generate_p4_params.py from config/default.yaml
// Do not edit manually.

#ifndef GENERATED_PARAMS_P4
#define GENERATED_PARAMS_P4

// --- Queue Configuration ---
#define Q_EVENT     {q_event}
#define Q_RELEASE   {q_release}

// --- Predictor Parameters ---
#define EPOCH_US          {epoch_us}
#define EWMA_ALPHA_SHIFT  {ewma_alpha_shift}
#define NEAR_HORIZON      {near_horizon}
#define FAR_HORIZON       {far_horizon}

// --- FSM Parameters ---
#define RECOVERY_EPOCHS   {recovery_epochs}
#define GAP_RESET_US      {gap_reset_us}
#define IDLE_RESET_US     {idle_reset_us}

// --- Sampling ---
#define QUIET_MASK        {quiet_mask}
#define WATCH_MASK        {watch_mask}

// --- Freshness ---
#define MAX_SILENCE_US    {max_silence_us}

// --- Delta Trigger ---
#define DELTA_THRESHOLD   {delta_threshold}

// --- Packet Format ---
#define MAX_HOPS          {max_hops}
#define INT_PORT          {int_port}
#define PTT_MAGIC         {ptt_magic}
#define PTT_VERSION       {ptt_version}

// --- Switch ID (overridden per-switch via -D) ---
#ifndef SWITCH_ID
#define SWITCH_ID         1
#endif

#endif // GENERATED_PARAMS_P4
"""


def main():
    repo_root = Path(__file__).resolve().parent.parent
    config_path = repo_root / "config" / "default.yaml"
    output_path = repo_root / "p4src" / "generated_params.p4"

    if not config_path.exists():
        print(f"ERROR: config not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    with open(config_path) as f:
        cfg = yaml.safe_load(f)

    q = cfg["queue"]
    p = cfg["predictor"]
    fsm = cfg["fsm"]
    samp = cfg["sampling"]
    fresh = cfg["freshness"]
    pkt = cfg["packet"]
    delta_cfg = cfg["delta"]

    gap_reset_us = fsm["gap_reset_multiple"] * p["epoch_us"]
    idle_reset_us = fsm["idle_reset_multiple"] * p["epoch_us"]

    content = TEMPLATE.format(
        q_event=q["event_threshold_packets"],
        q_release=q["release_threshold_packets"],
        epoch_us=p["epoch_us"],
        ewma_alpha_shift=p["ewma_alpha_shift"],
        near_horizon=p["near_horizon"],
        far_horizon=p["far_horizon"],
        recovery_epochs=fsm["recovery_epochs"],
        gap_reset_us=gap_reset_us,
        idle_reset_us=idle_reset_us,
        quiet_mask=samp["quiet_mask"],
        watch_mask=samp["watch_mask"],
        max_silence_us=fresh["max_silence_us"],
        delta_threshold=delta_cfg["threshold_packets"],
        max_hops=pkt["max_hops"],
        int_port=pkt["int_port"],
        ptt_magic=pkt["magic"],
        ptt_version=pkt["version"],
    )

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
