// PTT-INT: Generated parameters
// Auto-generated by control/generate_p4_params.py from config/default.yaml
// Do not edit manually.

#ifndef GENERATED_PARAMS_P4
#define GENERATED_PARAMS_P4

// --- Queue Configuration ---
#define Q_EVENT     96
#define Q_RELEASE   64

// --- Predictor Parameters ---
#define EPOCH_US          5000
#define EWMA_ALPHA_SHIFT  2
#define NEAR_HORIZON      2
#define FAR_HORIZON       8

// --- FSM Parameters ---
#define RECOVERY_EPOCHS   3
#define GAP_RESET_US      20000
#define IDLE_RESET_US     100000

// --- Sampling ---
#define QUIET_MASK        31
#define WATCH_MASK        3

// --- Freshness ---
#define MAX_SILENCE_US    100000

// --- Delta Trigger ---
#define DELTA_THRESHOLD   10

// --- Packet Format ---
#define MAX_HOPS          8
#define INT_PORT          32768
#define PTT_MAGIC         20564
#define PTT_VERSION       1

// --- Switch ID (overridden per-switch via -D) ---
#ifndef SWITCH_ID
#define SWITCH_ID         1
#endif

#endif // GENERATED_PARAMS_P4
